apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentence
spec:
  selector:
    matchLabels:
      app: sentence
  replicas: 1
  template:
    metadata:
      labels:
        app: sentence
    spec:
      containers:
      - name: sentence-sentence-alt
        image: chrimic/sentence-sentence-alt:latest
        ports:
        - containerPort: 8080
