apiVersion: apps/v1
kind: Deployment
metadata:
  name: verb
spec:
  selector:
    matchLabels:
      app: verb
  replicas: 1
  template:
    metadata:
      labels:
        app: verb
    spec:
      containers:
      - name: sentence-word-service-alt
        image: chrimic/sentence-word-service-alt:latest
        args: ["-jar", "-Dspring.profiles.active=verb", "word.jar"]
        ports:
        - containerPort: 8080
